#ifndef RESOURCE_ID_H
#define RESOURCE_ID_H

//	TEX
#define TEX_BAGDLG_GOLD_SMALL				27
#define TEX_BAGDLG_GOLD_MIDDLE				28
#define TEX_BAGDLG_GOLD_BIG					29
#define TEX_BAGDLG_BACK						3

#define TEX_ATTRIBDLG_BACK					380
#define TEX_ATTRIBDLG_BTNDOWN				396
#define TEX_ATTRIBDLG_BTNUP					398
#define TEX_ATTRIBDLG_EQUIPMAN				376
#define TEX_ATTRIBDLG_EQUIPWOMAN			377

#define TEX_MAINOPTUI_NUM1					31
#define TEX_MAINOPTUI_NUM6					36

#define TEX_HUM_HPTUBEBLANK					0
#define TEX_HUM_HPTUBEFULL					1

#define TEX_ANI_DC_STONE_BEGIN				60
#define TEX_ANI_DC_STONE_END				72
#define TEX_ANI_DC_BEGIN					40
#define TEX_ANI_DC_END						55

#define TEX_ANI_MC_STONE_BEGIN				100
#define TEX_ANI_MC_STONE_END				112
#define TEX_ANI_MC_BEGIN					80
#define TEX_ANI_MC_END						95

#define TEX_ANI_SC_STONE_BEGIN				140
#define TEX_ANI_SC_STONE_END				152
#define TEX_ANI_SC_BEGIN					120
#define TEX_ANI_SC_END						135

#define TEX_HUMPAGE_MALE					28
#define TEX_HUMPAGE_FEMALE					29
#define TEX_HUMHAIR_MALE					41
#define TEX_HUMHAIR_FEMALE					40

#define TEX_HPMP_BAR						148
#define ALIGN_HPMP_HP_LEFT					0
#define ALIGN_HPMP_HP_TOP					(450 + 30)
#define ALIGN_HPMP_MP_LEFT					50
#define ALIGN_HPMP_MP_TOP					(450 + 30)

#define TEX_EXPR_BAR						155
#define ALIGN_EXPR_LEFT						9
#define ALIGN_EXPR_TOP						(450 + 143)

//	The coordinates of MainOptUI 
#define TEX_MAINOPTUI_NEW					130
#define TEX_HUMBTN							133
#define TEX_BAGBTN							136
#define TEX_SKILLBTN						139
#define TEX_QUESTBTN						142
#define TEX_HANDMADEBTN						145
#define TEX_SYSMENUBTN						149

#define ALIGN_HUMBTN_LEFT					(680 + 1)
#define ALIGN_HUMBTN_TOP					(450 + 75 + 1)
#define ALIGN_BAGBTN_LEFT					(703 + 1)
#define ALIGN_BAGBTN_TOP					(450 + 75 + 1)
#define ALIGN_SKILLBTN_LEFT					(726 + 1)
#define ALIGN_SKILLBTN_TOP					(450 + 75 + 1)
#define ALIGN_QUESTBTN_LEFT					(749 + 1)
#define ALIGN_QUESTBTN_TOP					(450 + 75 + 1)
#define ALIGN_HANDMADEBTN_LEFT				(772 + 1)
#define ALIGN_HANDMADEBTN_TOP				(450 + 75 + 1)
#define ALIGN_SYSMENUBTN_LEFT				(641)
#define ALIGN_SYSMENUBTN_TOP				(450 + 67)

#define TEX_ASSISTMAIN_HORIZ				159
#define TEX_ASSISTMAIN_VERTICAL				171
#define TEX_ASSISTSHOWHIDE_HORIZ			156
#define TEX_ASSISTSHOWHIDE_VERTICAL			174
#define TEX_ASSISTTRANSFORM					165
#define TEX_ASSISTCLOSE						162

#define TEX_DECOMPOSE						177

#define TEX_ITEMFLASH						410

#define TEX_CHECKBOX						228
//#define TEX_CHECKBOX						229

#define TEX_UPARROW							292
#define TEX_DOWNARROW						294


//	ITEM ID
#define ITID_RANDOMSCROLL					408

#endif